openapi: 3.0.0
info:
  title: Api-Serverless-NodeJs
  description: Documentación del API Tasks
  version: 1.0.0
servers:
  - url: 'https://tk0tejv4e6.execute-api.us-east-1.amazonaws.com'
paths:
  /api/tasks:
    get:
      summary: Obtener todas las Tasks
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    post:
      summary: Crear una Task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '200':
          description: Almacenado correctamente
  /api/tasks/{id}:
    get:
      summary: Obtener una Task por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        descripcion:
          type: string
        createdAt:
          type: string
    TaskInput:
      type: object
      properties:
        nombre:
          type: string
        descripcion:
          type: string
      required:
        - nombre
        - descripcion
